[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.4.5",
    "langsmith>=0.3.42",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

